FROM python:3.9-slim

WORKDIR /app
COPY inventory/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY protobuf ./protobuf
COPY inventory ./inventory

WORKDIR /app/inventory
RUN python -m grpc_tools.protoc -I../protobuf --python_out=. --grpc_python_out=. ../protobuf/inventory.proto

EXPOSE 50051
CMD ["python", "server.py"]
